Document: cnweather
Title: Debian cnweather Manual
Author: <insert document author here>
Abstract: This manual describes what cnweather is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cnweather/cnweather.sgml.gz

Format: postscript
Files: /usr/share/doc/cnweather/cnweather.ps.gz

Format: text
Files: /usr/share/doc/cnweather/cnweather.text.gz

Format: HTML
Index: /usr/share/doc/cnweather/html/index.html
Files: /usr/share/doc/cnweather/html/*.html
